const BOSS_DAILY_THRESHOLD=50;
const bossDailyKey='wm_studio_v1_boss_daily';
let awardingBossReward=false;
function bossDay(){const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function readBossDaily(){let s;try{s=JSON.parse(localStorage.getItem(bossDailyKey)||'null')}catch{}return s&&s.day===bossDay()&&Number.isFinite(s.exp)&&s.exp>=0?{day:s.day,exp:s.exp,attempted:s.attempted===true,rewarded:s.rewarded===true}:{day:bossDay(),exp:0,attempted:false,rewarded:false}}
function saveBossDaily(s){localStorage.setItem(bossDailyKey,JSON.stringify(s));renderBossEntry()}
function noteBossDailyExp(amount){if(awardingBossReward||!Number.isFinite(amount)||amount<=0)return;const s=readBossDaily();s.exp+=amount;saveBossDaily(s)}
function renderBossEntry(){const host=document.getElementById('daily-boss-entry');if(!host)return;const s=readBossDaily();host.hidden=s.exp<BOSS_DAILY_THRESHOLD;if(host.hidden)return;host.innerHTML=`<div><strong>${s.attempted?'今日のボス戦は終了':'ボスが現れた！'}</strong><span>${s.attempted?'次の挑戦は明日':'１日１回 · 撃破30 EXP'}</span></div><button onclick="openDailyBoss()" ${s.attempted?'disabled':''}>${s.attempted?'挑戦済み ✓':'ボス戦へ →'}</button>`}
function openDailyBoss(){const s=readBossDaily();if(s.exp<BOSS_DAILY_THRESHOLD||s.attempted)return;const modal=document.createElement('div');modal.id='daily-boss-modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','ボス戦');modal.innerHTML='<button class="boss-close" onclick="closeDailyBoss()" aria-label="ボス戦を閉じる">✕</button><iframe title="相棒とボス戦" src="boss-demo.html?daily=1&v=6"></iframe>';document.body.append(modal);modal.querySelector('button').focus();window.dailyBossBridge={getSetup(){const state=getCompanionState(),c=companionCatalog.find(c=>c.id===state.active),g=companionGrowth(state.owned[c.id].xp);return {category:currentCategory,name:c.name,image:companionArtImage(c,g),exp:readBossDaily().exp}},async claim(){const claim=()=>{const s=readBossDaily();if(s.exp<BOSS_DAILY_THRESHOLD||s.attempted)return false;s.attempted=true;try{saveBossDaily(s);return true}catch{return false}};return navigator.locks? navigator.locks.request(bossDailyKey,claim):claim()},reward(){const s=readBossDaily();if(!s.attempted||s.rewarded)return false;s.rewarded=true;saveBossDaily(s);awardingBossReward=true;try{addExp(30)}finally{awardingBossReward=false}return true}}}
function companionArtImage(c,g){const host=document.createElement('div');host.innerHTML=companionArt(c,true,g);return host.querySelector('img')?.getAttribute('src')||'assets/buddy-blue-dragon.png'}
function closeDailyBoss(){document.getElementById('daily-boss-modal')?.remove();delete window.dailyBossBridge;renderBossEntry();document.querySelector('#daily-boss-entry button')?.focus()}
window.addEventListener('storage',e=>{if(e.key===bossDailyKey)renderBossEntry()});window.addEventListener('focus',renderBossEntry);setInterval(renderBossEntry,60000);renderBossEntry();
